# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Enums/FortEnums.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Enums/FortEnums.proto',
  package='Protos.Enums',
  syntax='proto3',
  serialized_pb=_b('\n\x15\x45nums/FortEnums.proto\x12\x0cProtos.Enums*B\n\x0b\x46ortSponser\x12\x11\n\rUNSET_SPONSOR\x10\x00\x12\r\n\tMCDONALDS\x10\x01\x12\x11\n\rPOKEMON_STORE\x10\x02*#\n\x08\x46ortType\x12\x07\n\x03GYM\x10\x00\x12\x0e\n\nCHECKPOINT\x10\x01*3\n\x11\x46ortRenderingType\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x11\n\rINTERNAL_TEST\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FORTSPONSER = _descriptor.EnumDescriptor(
  name='FortSponser',
  full_name='Protos.Enums.FortSponser',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET_SPONSOR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MCDONALDS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKEMON_STORE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=39,
  serialized_end=105,
)
_sym_db.RegisterEnumDescriptor(_FORTSPONSER)

FortSponser = enum_type_wrapper.EnumTypeWrapper(_FORTSPONSER)
_FORTTYPE = _descriptor.EnumDescriptor(
  name='FortType',
  full_name='Protos.Enums.FortType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GYM', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHECKPOINT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=107,
  serialized_end=142,
)
_sym_db.RegisterEnumDescriptor(_FORTTYPE)

FortType = enum_type_wrapper.EnumTypeWrapper(_FORTTYPE)
_FORTRENDERINGTYPE = _descriptor.EnumDescriptor(
  name='FortRenderingType',
  full_name='Protos.Enums.FortRenderingType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_TEST', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=144,
  serialized_end=195,
)
_sym_db.RegisterEnumDescriptor(_FORTRENDERINGTYPE)

FortRenderingType = enum_type_wrapper.EnumTypeWrapper(_FORTRENDERINGTYPE)
UNSET_SPONSOR = 0
MCDONALDS = 1
POKEMON_STORE = 2
GYM = 0
CHECKPOINT = 1
DEFAULT = 0
INTERNAL_TEST = 1


DESCRIPTOR.enum_types_by_name['FortSponser'] = _FORTSPONSER
DESCRIPTOR.enum_types_by_name['FortType'] = _FORTTYPE
DESCRIPTOR.enum_types_by_name['FortRenderingType'] = _FORTRENDERINGTYPE


# @@protoc_insertion_point(module_scope)
