# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Enums/InventoryEnums.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Enums/InventoryEnums.proto',
  package='Protos.Enums',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x45nums/InventoryEnums.proto\x12\x0cProtos.Enums*\xb6\x04\n\x06ItemId\x12\x10\n\x0cUNKNOWN_ITEM\x10\x00\x12\r\n\tPOKE_BALL\x10\x01\x12\x0e\n\nGREAT_BALL\x10\x02\x12\x0e\n\nULTRA_BALL\x10\x03\x12\x0f\n\x0bMASTER_BALL\x10\x04\x12\n\n\x06POTION\x10\x65\x12\x10\n\x0cSUPER_POTION\x10\x66\x12\x10\n\x0cHYPER_POTION\x10g\x12\x0e\n\nMAX_POTION\x10h\x12\x0b\n\x06REVIVE\x10\xc9\x01\x12\x0f\n\nMAX_REVIVE\x10\xca\x01\x12\x0e\n\tLUCKY_EGG\x10\xad\x02\x12\x15\n\x10INCENSE_ORDINARY\x10\x91\x03\x12\x12\n\rINCENSE_SPICY\x10\x92\x03\x12\x11\n\x0cINCENSE_COOL\x10\x93\x03\x12\x13\n\x0eINCENSE_FLORAL\x10\x94\x03\x12\x0e\n\tTROY_DISK\x10\xf5\x03\x12\r\n\x08X_ATTACK\x10\xda\x04\x12\x0e\n\tX_DEFENSE\x10\xdb\x04\x12\x0e\n\tX_MIRACLE\x10\xdc\x04\x12\x0f\n\nRAZZ_BERRY\x10\xbd\x05\x12\x0f\n\nBLUK_BERRY\x10\xbe\x05\x12\x10\n\x0bNANAB_BERRY\x10\xbf\x05\x12\x10\n\x0bWEPAR_BERRY\x10\xc0\x05\x12\x10\n\x0bPINAP_BERRY\x10\xc1\x05\x12\x13\n\x0eSPECIAL_CAMERA\x10\xa1\x06\x12\x1e\n\x19INCUBATOR_BASIC_UNLIMITED\x10\x85\x07\x12\x14\n\x0fINCUBATOR_BASIC\x10\x86\x07\x12\x1c\n\x17POKEMON_STORAGE_UPGRADE\x10\xe9\x07\x12\x19\n\x14ITEM_STORAGE_UPGRADE\x10\xea\x07\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ITEMID = _descriptor.EnumDescriptor(
  name='ItemId',
  full_name='Protos.Enums.ItemId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ITEM', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKE_BALL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREAT_BALL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ULTRA_BALL', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MASTER_BALL', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POTION', index=5, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUPER_POTION', index=6, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HYPER_POTION', index=7, number=103,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX_POTION', index=8, number=104,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REVIVE', index=9, number=201,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX_REVIVE', index=10, number=202,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LUCKY_EGG', index=11, number=301,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCENSE_ORDINARY', index=12, number=401,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCENSE_SPICY', index=13, number=402,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCENSE_COOL', index=14, number=403,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCENSE_FLORAL', index=15, number=404,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TROY_DISK', index=16, number=501,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X_ATTACK', index=17, number=602,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X_DEFENSE', index=18, number=603,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X_MIRACLE', index=19, number=604,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAZZ_BERRY', index=20, number=701,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUK_BERRY', index=21, number=702,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NANAB_BERRY', index=22, number=703,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEPAR_BERRY', index=23, number=704,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PINAP_BERRY', index=24, number=705,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIAL_CAMERA', index=25, number=801,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCUBATOR_BASIC_UNLIMITED', index=26, number=901,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCUBATOR_BASIC', index=27, number=902,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKEMON_STORAGE_UPGRADE', index=28, number=1001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_STORAGE_UPGRADE', index=29, number=1002,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=45,
  serialized_end=611,
)
_sym_db.RegisterEnumDescriptor(_ITEMID)

ItemId = enum_type_wrapper.EnumTypeWrapper(_ITEMID)
UNKNOWN_ITEM = 0
POKE_BALL = 1
GREAT_BALL = 2
ULTRA_BALL = 3
MASTER_BALL = 4
POTION = 101
SUPER_POTION = 102
HYPER_POTION = 103
MAX_POTION = 104
REVIVE = 201
MAX_REVIVE = 202
LUCKY_EGG = 301
INCENSE_ORDINARY = 401
INCENSE_SPICY = 402
INCENSE_COOL = 403
INCENSE_FLORAL = 404
TROY_DISK = 501
X_ATTACK = 602
X_DEFENSE = 603
X_MIRACLE = 604
RAZZ_BERRY = 701
BLUK_BERRY = 702
NANAB_BERRY = 703
WEPAR_BERRY = 704
PINAP_BERRY = 705
SPECIAL_CAMERA = 801
INCUBATOR_BASIC_UNLIMITED = 901
INCUBATOR_BASIC = 902
POKEMON_STORAGE_UPGRADE = 1001
ITEM_STORAGE_UPGRADE = 1002


DESCRIPTOR.enum_types_by_name['ItemId'] = _ITEMID


# @@protoc_insertion_point(module_scope)
