# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Map/Pokemon/OneStepPokemon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Enums import PokemonEnums_pb2 as Enums_dot_PokemonEnums__pb2

from Enums.PokemonEnums_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Map/Pokemon/OneStepPokemon.proto',
  package='Protos.Map.Pokemon',
  syntax='proto3',
  serialized_pb=_b('\n Map/Pokemon/OneStepPokemon.proto\x12\x12Protos.Map.Pokemon\x1a\x18\x45nums/PokemonEnums.proto\"\xb0\x01\n\x0eOneStepPokemon\x12\x15\n\rspawnpoint_id\x18\x01 \x01(\t\x12\x14\n\x0c\x65ncounter_id\x18\x02 \x01(\x06\x12+\n\npokemon_id\x18\x03 \x01(\x0e\x32\x17.Protos.Enums.PokemonId\x12\x1f\n\x17\x65xpiration_timestamp_ms\x18\x04 \x01(\x03\x12\x10\n\x08latitude\x18\x05 \x01(\x01\x12\x11\n\tlongitude\x18\x06 \x01(\x01P\x00\x62\x06proto3')
  ,
  dependencies=[Enums_dot_PokemonEnums__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ONESTEPPOKEMON = _descriptor.Descriptor(
  name='OneStepPokemon',
  full_name='Protos.Map.Pokemon.OneStepPokemon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spawnpoint_id', full_name='Protos.Map.Pokemon.OneStepPokemon.spawnpoint_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encounter_id', full_name='Protos.Map.Pokemon.OneStepPokemon.encounter_id', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokemon_id', full_name='Protos.Map.Pokemon.OneStepPokemon.pokemon_id', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiration_timestamp_ms', full_name='Protos.Map.Pokemon.OneStepPokemon.expiration_timestamp_ms', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Protos.Map.Pokemon.OneStepPokemon.latitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Protos.Map.Pokemon.OneStepPokemon.longitude', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=259,
)

_ONESTEPPOKEMON.fields_by_name['pokemon_id'].enum_type = Enums_dot_PokemonEnums__pb2._POKEMONID
DESCRIPTOR.message_types_by_name['OneStepPokemon'] = _ONESTEPPOKEMON

OneStepPokemon = _reflection.GeneratedProtocolMessageType('OneStepPokemon', (_message.Message,), dict(
  DESCRIPTOR = _ONESTEPPOKEMON,
  __module__ = 'Map.Pokemon.OneStepPokemon_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Map.Pokemon.OneStepPokemon)
  ))
_sym_db.RegisterMessage(OneStepPokemon)


# @@protoc_insertion_point(module_scope)
