# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Map/Pokemon/TwoStepsPokemon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Pokemon import PokemonDetails_pb2 as Pokemon_dot_PokemonDetails__pb2
Enums_dot_PokemonEnums__pb2 = Pokemon_dot_PokemonDetails__pb2.Enums_dot_PokemonEnums__pb2
Enums_dot_InventoryEnums__pb2 = Pokemon_dot_PokemonDetails__pb2.Enums_dot_InventoryEnums__pb2

from Pokemon.PokemonDetails_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Map/Pokemon/TwoStepsPokemon.proto',
  package='Protos.Map.Pokemon',
  syntax='proto3',
  serialized_pb=_b('\n!Map/Pokemon/TwoStepsPokemon.proto\x12\x12Protos.Map.Pokemon\x1a\x1cPokemon/PokemonDetails.proto\"\xde\x01\n\x0fTwoStepsPokemon\x12\x14\n\x0c\x65ncounter_id\x18\x01 \x01(\x06\x12\"\n\x1alast_modified_timestamp_ms\x18\x02 \x01(\x03\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x16\n\x0espawn_point_id\x18\x05 \x01(\t\x12\x37\n\x0fpokemon_details\x18\x07 \x01(\x0b\x32\x1e.Protos.Pokemon.PokemonDetails\x12\x1b\n\x13time_till_hidden_ms\x18\x0b \x01(\x05P\x00\x62\x06proto3')
  ,
  dependencies=[Pokemon_dot_PokemonDetails__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TWOSTEPSPOKEMON = _descriptor.Descriptor(
  name='TwoStepsPokemon',
  full_name='Protos.Map.Pokemon.TwoStepsPokemon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encounter_id', full_name='Protos.Map.Pokemon.TwoStepsPokemon.encounter_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_modified_timestamp_ms', full_name='Protos.Map.Pokemon.TwoStepsPokemon.last_modified_timestamp_ms', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Protos.Map.Pokemon.TwoStepsPokemon.latitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Protos.Map.Pokemon.TwoStepsPokemon.longitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spawn_point_id', full_name='Protos.Map.Pokemon.TwoStepsPokemon.spawn_point_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokemon_details', full_name='Protos.Map.Pokemon.TwoStepsPokemon.pokemon_details', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_till_hidden_ms', full_name='Protos.Map.Pokemon.TwoStepsPokemon.time_till_hidden_ms', index=6,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=310,
)

_TWOSTEPSPOKEMON.fields_by_name['pokemon_details'].message_type = Pokemon_dot_PokemonDetails__pb2._POKEMONDETAILS
DESCRIPTOR.message_types_by_name['TwoStepsPokemon'] = _TWOSTEPSPOKEMON

TwoStepsPokemon = _reflection.GeneratedProtocolMessageType('TwoStepsPokemon', (_message.Message,), dict(
  DESCRIPTOR = _TWOSTEPSPOKEMON,
  __module__ = 'Map.Pokemon.TwoStepsPokemon_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Map.Pokemon.TwoStepsPokemon)
  ))
_sym_db.RegisterMessage(TwoStepsPokemon)


# @@protoc_insertion_point(module_scope)
