# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Responses/CatchPokemonResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Enums import PokemonEnums_pb2 as Enums_dot_PokemonEnums__pb2
from Pokemon import CaptureScore_pb2 as Pokemon_dot_CaptureScore__pb2
Enums_dot_PlayerEnums__pb2 = Pokemon_dot_CaptureScore__pb2.Enums_dot_PlayerEnums__pb2

from Enums.PokemonEnums_pb2 import *
from Pokemon.CaptureScore_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Responses/CatchPokemonResponse.proto',
  package='Protos.Responses',
  syntax='proto3',
  serialized_pb=_b('\n$Responses/CatchPokemonResponse.proto\x12\x10Protos.Responses\x1a\x18\x45nums/PokemonEnums.proto\x1a\x1aPokemon/CaptureScore.proto\"\xa2\x01\n\x14\x43\x61tchPokemonResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.Protos.Enums.CatchStatus\x12\x14\n\x0cmiss_percent\x18\x02 \x01(\x01\x12\x1b\n\x13\x63\x61ptured_pokemon_id\x18\x03 \x01(\x06\x12,\n\x06scores\x18\x04 \x01(\x0b\x32\x1c.Protos.Pokemon.CaptureScoreP\x00P\x01\x62\x06proto3')
  ,
  dependencies=[Enums_dot_PokemonEnums__pb2.DESCRIPTOR,Pokemon_dot_CaptureScore__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CATCHPOKEMONRESPONSE = _descriptor.Descriptor(
  name='CatchPokemonResponse',
  full_name='Protos.Responses.CatchPokemonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Protos.Responses.CatchPokemonResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='miss_percent', full_name='Protos.Responses.CatchPokemonResponse.miss_percent', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='captured_pokemon_id', full_name='Protos.Responses.CatchPokemonResponse.captured_pokemon_id', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scores', full_name='Protos.Responses.CatchPokemonResponse.scores', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=275,
)

_CATCHPOKEMONRESPONSE.fields_by_name['status'].enum_type = Enums_dot_PokemonEnums__pb2._CATCHSTATUS
_CATCHPOKEMONRESPONSE.fields_by_name['scores'].message_type = Pokemon_dot_CaptureScore__pb2._CAPTURESCORE
DESCRIPTOR.message_types_by_name['CatchPokemonResponse'] = _CATCHPOKEMONRESPONSE

CatchPokemonResponse = _reflection.GeneratedProtocolMessageType('CatchPokemonResponse', (_message.Message,), dict(
  DESCRIPTOR = _CATCHPOKEMONRESPONSE,
  __module__ = 'Responses.CatchPokemonResponse_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Responses.CatchPokemonResponse)
  ))
_sym_db.RegisterMessage(CatchPokemonResponse)


# @@protoc_insertion_point(module_scope)
