# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Responses/EncounterResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Pokemon import Pokemon_pb2 as Pokemon_dot_Pokemon__pb2
Enums_dot_PokemonEnums__pb2 = Pokemon_dot_Pokemon__pb2.Enums_dot_PokemonEnums__pb2

from Pokemon.Pokemon_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Responses/EncounterResponse.proto',
  package='Protos.Responses',
  syntax='proto3',
  serialized_pb=_b('\n!Responses/EncounterResponse.proto\x12\x10Protos.Responses\x1a\x15Pokemon/Pokemon.proto\"\xb6\x01\n\x11\x45ncounterResponse\x12\x14\n\x0c\x65ncounter_id\x18\x01 \x01(\x06\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x16\n\x0espawn_point_id\x18\x05 \x01(\t\x12(\n\x07pokemon\x18\x07 \x01(\x0b\x32\x17.Protos.Pokemon.Pokemon\x12\x11\n\tunknown11\x18\x0b \x01(\x05P\x00\x62\x06proto3')
  ,
  dependencies=[Pokemon_dot_Pokemon__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENCOUNTERRESPONSE = _descriptor.Descriptor(
  name='EncounterResponse',
  full_name='Protos.Responses.EncounterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encounter_id', full_name='Protos.Responses.EncounterResponse.encounter_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Protos.Responses.EncounterResponse.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Protos.Responses.EncounterResponse.latitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Protos.Responses.EncounterResponse.longitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spawn_point_id', full_name='Protos.Responses.EncounterResponse.spawn_point_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokemon', full_name='Protos.Responses.EncounterResponse.pokemon', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown11', full_name='Protos.Responses.EncounterResponse.unknown11', index=6,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=261,
)

_ENCOUNTERRESPONSE.fields_by_name['pokemon'].message_type = Pokemon_dot_Pokemon__pb2._POKEMON
DESCRIPTOR.message_types_by_name['EncounterResponse'] = _ENCOUNTERRESPONSE

EncounterResponse = _reflection.GeneratedProtocolMessageType('EncounterResponse', (_message.Message,), dict(
  DESCRIPTOR = _ENCOUNTERRESPONSE,
  __module__ = 'Responses.EncounterResponse_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Responses.EncounterResponse)
  ))
_sym_db.RegisterMessage(EncounterResponse)


# @@protoc_insertion_point(module_scope)
