# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Responses/FortSearchResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Pokemon import Pokemon_pb2 as Pokemon_dot_Pokemon__pb2
Enums_dot_PokemonEnums__pb2 = Pokemon_dot_Pokemon__pb2.Enums_dot_PokemonEnums__pb2
from Enums import PlayerEnums_pb2 as Enums_dot_PlayerEnums__pb2
from Enums import FortEnums_pb2 as Enums_dot_FortEnums__pb2

from Pokemon.Pokemon_pb2 import *
from Enums.PlayerEnums_pb2 import *
from Enums.FortEnums_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Responses/FortSearchResponse.proto',
  package='Protos.Networking.Responses',
  syntax='proto3',
  serialized_pb=_b('\n\"Responses/FortSearchResponse.proto\x12\x1bProtos.Networking.Responses\x1a\x15Pokemon/Pokemon.proto\x1a\x17\x45nums/PlayerEnums.proto\x1a\x15\x45nums/FortEnums.proto\"\xa7\x02\n\x12\x46ortSearchResponse\x12.\n\x06result\x18\x01 \x01(\x0e\x32\x1e.Protos.Enums.FortSearchResult\x12=\n\ritems_awarded\x18\x02 \x03(\x0b\x32&.Protos.Networking.Responses.ItemAward\x12\x14\n\x0cgems_awarded\x18\x03 \x01(\x05\x12,\n\x0bpokemon_egg\x18\x04 \x01(\x0b\x32\x17.Protos.Pokemon.Pokemon\x12\x12\n\nxp_awarded\x18\x05 \x01(\x05\x12&\n\x1e\x63ooldown_complete_timestamp_ms\x18\x06 \x01(\x03\x12\"\n\x1a\x63hain_hack_sequence_number\x18\x07 \x01(\x05\"J\n\tItemAward\x12)\n\titem_type\x18\x01 \x01(\x0e\x32\x16.Protos.Enums.ItemType\x12\x12\n\nitem_count\x18\x02 \x01(\x05P\x00P\x01P\x02\x62\x06proto3')
  ,
  dependencies=[Pokemon_dot_Pokemon__pb2.DESCRIPTOR,Enums_dot_PlayerEnums__pb2.DESCRIPTOR,Enums_dot_FortEnums__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FORTSEARCHRESPONSE = _descriptor.Descriptor(
  name='FortSearchResponse',
  full_name='Protos.Networking.Responses.FortSearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='Protos.Networking.Responses.FortSearchResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items_awarded', full_name='Protos.Networking.Responses.FortSearchResponse.items_awarded', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gems_awarded', full_name='Protos.Networking.Responses.FortSearchResponse.gems_awarded', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokemon_egg', full_name='Protos.Networking.Responses.FortSearchResponse.pokemon_egg', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xp_awarded', full_name='Protos.Networking.Responses.FortSearchResponse.xp_awarded', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cooldown_complete_timestamp_ms', full_name='Protos.Networking.Responses.FortSearchResponse.cooldown_complete_timestamp_ms', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chain_hack_sequence_number', full_name='Protos.Networking.Responses.FortSearchResponse.chain_hack_sequence_number', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=434,
)


_ITEMAWARD = _descriptor.Descriptor(
  name='ItemAward',
  full_name='Protos.Networking.Responses.ItemAward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_type', full_name='Protos.Networking.Responses.ItemAward.item_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_count', full_name='Protos.Networking.Responses.ItemAward.item_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=510,
)

_FORTSEARCHRESPONSE.fields_by_name['result'].enum_type = Enums_dot_FortEnums__pb2._FORTSEARCHRESULT
_FORTSEARCHRESPONSE.fields_by_name['items_awarded'].message_type = _ITEMAWARD
_FORTSEARCHRESPONSE.fields_by_name['pokemon_egg'].message_type = Pokemon_dot_Pokemon__pb2._POKEMON
_ITEMAWARD.fields_by_name['item_type'].enum_type = Enums_dot_PlayerEnums__pb2._ITEMTYPE
DESCRIPTOR.message_types_by_name['FortSearchResponse'] = _FORTSEARCHRESPONSE
DESCRIPTOR.message_types_by_name['ItemAward'] = _ITEMAWARD

FortSearchResponse = _reflection.GeneratedProtocolMessageType('FortSearchResponse', (_message.Message,), dict(
  DESCRIPTOR = _FORTSEARCHRESPONSE,
  __module__ = 'Responses.FortSearchResponse_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Networking.Responses.FortSearchResponse)
  ))
_sym_db.RegisterMessage(FortSearchResponse)

ItemAward = _reflection.GeneratedProtocolMessageType('ItemAward', (_message.Message,), dict(
  DESCRIPTOR = _ITEMAWARD,
  __module__ = 'Responses.FortSearchResponse_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Networking.Responses.ItemAward)
  ))
_sym_db.RegisterMessage(ItemAward)


# @@protoc_insertion_point(module_scope)
