# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Responses/GetInventoryResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Player import InventoryDelta_pb2 as Player_dot_InventoryDelta__pb2
Player_dot_InventoryItem__pb2 = Player_dot_InventoryDelta__pb2.Player_dot_InventoryItem__pb2
Player_dot_InventoryItemData__pb2 = Player_dot_InventoryDelta__pb2.Player_dot_InventoryItemData__pb2
Pokemon_dot_Pokemon__pb2 = Player_dot_InventoryDelta__pb2.Pokemon_dot_Pokemon__pb2
Enums_dot_PokemonEnums__pb2 = Player_dot_InventoryDelta__pb2.Enums_dot_PokemonEnums__pb2
Player_dot_Item__pb2 = Player_dot_InventoryDelta__pb2.Player_dot_Item__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryDelta__pb2.Enums_dot_PlayerEnums__pb2
Pokemon_dot_PokedexEntry__pb2 = Player_dot_InventoryDelta__pb2.Pokemon_dot_PokedexEntry__pb2
Player_dot_PlayerStats__pb2 = Player_dot_InventoryDelta__pb2.Player_dot_PlayerStats__pb2
Player_dot_PlayerCurrency__pb2 = Player_dot_InventoryDelta__pb2.Player_dot_PlayerCurrency__pb2
Player_dot_PlayerCamera__pb2 = Player_dot_InventoryDelta__pb2.Player_dot_PlayerCamera__pb2
Player_dot_InventoryUpgrade__pb2 = Player_dot_InventoryDelta__pb2.Player_dot_InventoryUpgrade__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryDelta__pb2.Enums_dot_PlayerEnums__pb2
Player_dot_AppliedItem__pb2 = Player_dot_InventoryDelta__pb2.Player_dot_AppliedItem__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryDelta__pb2.Enums_dot_PlayerEnums__pb2
Player_dot_EggIncubator__pb2 = Player_dot_InventoryDelta__pb2.Player_dot_EggIncubator__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryDelta__pb2.Enums_dot_PlayerEnums__pb2
Pokemon_dot_PokemonFamily__pb2 = Player_dot_InventoryDelta__pb2.Pokemon_dot_PokemonFamily__pb2
Enums_dot_PokemonEnums__pb2 = Player_dot_InventoryDelta__pb2.Enums_dot_PokemonEnums__pb2

from Player.InventoryDelta_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Responses/GetInventoryResponse.proto',
  package='Protos.Responses',
  syntax='proto3',
  serialized_pb=_b('\n$Responses/GetInventoryResponse.proto\x12\x10Protos.Responses\x1a\x1bPlayer/InventoryDelta.proto\"_\n\x14GetInventoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x36\n\x0finventory_delta\x18\x02 \x01(\x0b\x32\x1d.Protos.Player.InventoryDeltaP\x00\x62\x06proto3')
  ,
  dependencies=[Player_dot_InventoryDelta__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETINVENTORYRESPONSE = _descriptor.Descriptor(
  name='GetInventoryResponse',
  full_name='Protos.Responses.GetInventoryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='Protos.Responses.GetInventoryResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inventory_delta', full_name='Protos.Responses.GetInventoryResponse.inventory_delta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=182,
)

_GETINVENTORYRESPONSE.fields_by_name['inventory_delta'].message_type = Player_dot_InventoryDelta__pb2._INVENTORYDELTA
DESCRIPTOR.message_types_by_name['GetInventoryResponse'] = _GETINVENTORYRESPONSE

GetInventoryResponse = _reflection.GeneratedProtocolMessageType('GetInventoryResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETINVENTORYRESPONSE,
  __module__ = 'Responses.GetInventoryResponse_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Responses.GetInventoryResponse)
  ))
_sym_db.RegisterMessage(GetInventoryResponse)


# @@protoc_insertion_point(module_scope)
