# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Responses/GetMapObjectsResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Map import MapCell_pb2 as Map_dot_MapCell__pb2
Map_dot_SpawnPoint__pb2 = Map_dot_MapCell__pb2.Map_dot_SpawnPoint__pb2
Map_dot_Fort_dot_FortData__pb2 = Map_dot_MapCell__pb2.Map_dot_Fort_dot_FortData__pb2
Enums_dot_PlayerEnums__pb2 = Map_dot_MapCell__pb2.Enums_dot_PlayerEnums__pb2
Enums_dot_PokemonEnums__pb2 = Map_dot_MapCell__pb2.Enums_dot_PokemonEnums__pb2
Enums_dot_FortEnums__pb2 = Map_dot_MapCell__pb2.Enums_dot_FortEnums__pb2
Map_dot_Fort_dot_FortLureInfo__pb2 = Map_dot_MapCell__pb2.Map_dot_Fort_dot_FortLureInfo__pb2
Enums_dot_PokemonEnums__pb2 = Map_dot_MapCell__pb2.Enums_dot_PokemonEnums__pb2
Map_dot_Fort_dot_FortSummary__pb2 = Map_dot_MapCell__pb2.Map_dot_Fort_dot_FortSummary__pb2
Map_dot_Pokemon_dot_OneStepPokemon__pb2 = Map_dot_MapCell__pb2.Map_dot_Pokemon_dot_OneStepPokemon__pb2
Enums_dot_PokemonEnums__pb2 = Map_dot_MapCell__pb2.Enums_dot_PokemonEnums__pb2
Map_dot_Pokemon_dot_TwoStepsPokemon__pb2 = Map_dot_MapCell__pb2.Map_dot_Pokemon_dot_TwoStepsPokemon__pb2
Pokemon_dot_PokemonDetails__pb2 = Map_dot_MapCell__pb2.Pokemon_dot_PokemonDetails__pb2
Map_dot_Pokemon_dot_ThreeStepsPokemon__pb2 = Map_dot_MapCell__pb2.Map_dot_Pokemon_dot_ThreeStepsPokemon__pb2
Enums_dot_PokemonEnums__pb2 = Map_dot_MapCell__pb2.Enums_dot_PokemonEnums__pb2

from Map.MapCell_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Responses/GetMapObjectsResponse.proto',
  package='Protos.Responses',
  syntax='proto3',
  serialized_pb=_b('\n%Responses/GetMapObjectsResponse.proto\x12\x10Protos.Responses\x1a\x11Map/MapCell.proto\"O\n\x15GetMapObjectsResponse\x12&\n\tmap_tiles\x18\x01 \x03(\x0b\x32\x13.Protos.Map.MapCell\x12\x0e\n\x06Status\x18\x02 \x01(\x05P\x00\x62\x06proto3')
  ,
  dependencies=[Map_dot_MapCell__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETMAPOBJECTSRESPONSE = _descriptor.Descriptor(
  name='GetMapObjectsResponse',
  full_name='Protos.Responses.GetMapObjectsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='map_tiles', full_name='Protos.Responses.GetMapObjectsResponse.map_tiles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Status', full_name='Protos.Responses.GetMapObjectsResponse.Status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=157,
)

_GETMAPOBJECTSRESPONSE.fields_by_name['map_tiles'].message_type = Map_dot_MapCell__pb2._MAPCELL
DESCRIPTOR.message_types_by_name['GetMapObjectsResponse'] = _GETMAPOBJECTSRESPONSE

GetMapObjectsResponse = _reflection.GeneratedProtocolMessageType('GetMapObjectsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETMAPOBJECTSRESPONSE,
  __module__ = 'Responses.GetMapObjectsResponse_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Responses.GetMapObjectsResponse)
  ))
_sym_db.RegisterMessage(GetMapObjectsResponse)


# @@protoc_insertion_point(module_scope)
