# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResponseEnvelop.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EnvelopData_pb2 as EnvelopData__pb2

from EnvelopData_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='ResponseEnvelop.proto',
  package='Protos',
  syntax='proto3',
  serialized_pb=_b('\n\x15ResponseEnvelop.proto\x12\x06Protos\x1a\x11\x45nvelopData.proto\"\xa7\x01\n\x0fResponseEnvelop\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0e\n\x06rpc_id\x18\x02 \x01(\x03\x12\x0f\n\x07\x61pi_url\x18\x03 \x01(\t\x12\"\n\x08unknown6\x18\x06 \x01(\x0b\x32\x10.Protos.Unknown6\x12\'\n\x0b\x61uth_ticket\x18\x07 \x01(\x0b\x32\x12.Protos.AuthTicket\x12\x11\n\tresponses\x18\x64 \x03(\x0cP\x00\x62\x06proto3')
  ,
  dependencies=[EnvelopData__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESPONSEENVELOP = _descriptor.Descriptor(
  name='ResponseEnvelop',
  full_name='Protos.ResponseEnvelop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='Protos.ResponseEnvelop.status_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpc_id', full_name='Protos.ResponseEnvelop.rpc_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='api_url', full_name='Protos.ResponseEnvelop.api_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown6', full_name='Protos.ResponseEnvelop.unknown6', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth_ticket', full_name='Protos.ResponseEnvelop.auth_ticket', index=4,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responses', full_name='Protos.ResponseEnvelop.responses', index=5,
      number=100, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=220,
)

_RESPONSEENVELOP.fields_by_name['unknown6'].message_type = EnvelopData__pb2._UNKNOWN6
_RESPONSEENVELOP.fields_by_name['auth_ticket'].message_type = EnvelopData__pb2._AUTHTICKET
DESCRIPTOR.message_types_by_name['ResponseEnvelop'] = _RESPONSEENVELOP

ResponseEnvelop = _reflection.GeneratedProtocolMessageType('ResponseEnvelop', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEENVELOP,
  __module__ = 'ResponseEnvelop_pb2'
  # @@protoc_insertion_point(class_scope:Protos.ResponseEnvelop)
  ))
_sym_db.RegisterMessage(ResponseEnvelop)


# @@protoc_insertion_point(module_scope)
