# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Requests/CatchPokemonRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Enums import PlayerEnums_pb2 as Enums_dot_PlayerEnums__pb2

from Enums.PlayerEnums_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Requests/CatchPokemonRequest.proto',
  package='Protos.Requests',
  syntax='proto3',
  serialized_pb=_b('\n\"Requests/CatchPokemonRequest.proto\x12\x0fProtos.Requests\x1a\x17\x45nums/PlayerEnums.proto\"\xe1\x01\n\x13\x43\x61tchPokemonRequest\x12\x14\n\x0c\x65ncounter_id\x18\x01 \x01(\x06\x12,\n\x08pokeball\x18\x02 \x01(\x0e\x32\x1a.Protos.Enums.PokeballType\x12\x1f\n\x17normalized_reticle_size\x18\x03 \x01(\x01\x12\x18\n\x10spawn_point_guid\x18\x04 \x01(\t\x12\x13\n\x0bhit_pokemon\x18\x05 \x01(\x08\x12\x15\n\rspin_modifier\x18\x06 \x01(\x01\x12\x1f\n\x17normalized_hit_position\x18\x07 \x01(\x01P\x00\x62\x06proto3')
  ,
  dependencies=[Enums_dot_PlayerEnums__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CATCHPOKEMONREQUEST = _descriptor.Descriptor(
  name='CatchPokemonRequest',
  full_name='Protos.Requests.CatchPokemonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encounter_id', full_name='Protos.Requests.CatchPokemonRequest.encounter_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokeball', full_name='Protos.Requests.CatchPokemonRequest.pokeball', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normalized_reticle_size', full_name='Protos.Requests.CatchPokemonRequest.normalized_reticle_size', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spawn_point_guid', full_name='Protos.Requests.CatchPokemonRequest.spawn_point_guid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hit_pokemon', full_name='Protos.Requests.CatchPokemonRequest.hit_pokemon', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spin_modifier', full_name='Protos.Requests.CatchPokemonRequest.spin_modifier', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normalized_hit_position', full_name='Protos.Requests.CatchPokemonRequest.normalized_hit_position', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=306,
)

_CATCHPOKEMONREQUEST.fields_by_name['pokeball'].enum_type = Enums_dot_PlayerEnums__pb2._POKEBALLTYPE
DESCRIPTOR.message_types_by_name['CatchPokemonRequest'] = _CATCHPOKEMONREQUEST

CatchPokemonRequest = _reflection.GeneratedProtocolMessageType('CatchPokemonRequest', (_message.Message,), dict(
  DESCRIPTOR = _CATCHPOKEMONREQUEST,
  __module__ = 'Requests.CatchPokemonRequest_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Requests.CatchPokemonRequest)
  ))
_sym_db.RegisterMessage(CatchPokemonRequest)


# @@protoc_insertion_point(module_scope)
