# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Requests/EncounterRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Requests/EncounterRequest.proto',
  package='Protos.Requests',
  syntax='proto3',
  serialized_pb=_b('\n\x1fRequests/EncounterRequest.proto\x12\x0fProtos.Requests\"e\n\x10\x45ncounterRequest\x12\x14\n\x0c\x65ncounter_id\x18\x01 \x01(\x06\x12\x16\n\x0espawn_point_id\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENCOUNTERREQUEST = _descriptor.Descriptor(
  name='EncounterRequest',
  full_name='Protos.Requests.EncounterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encounter_id', full_name='Protos.Requests.EncounterRequest.encounter_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spawn_point_id', full_name='Protos.Requests.EncounterRequest.spawn_point_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Protos.Requests.EncounterRequest.latitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Protos.Requests.EncounterRequest.longitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['EncounterRequest'] = _ENCOUNTERREQUEST

EncounterRequest = _reflection.GeneratedProtocolMessageType('EncounterRequest', (_message.Message,), dict(
  DESCRIPTOR = _ENCOUNTERREQUEST,
  __module__ = 'Requests.EncounterRequest_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Requests.EncounterRequest)
  ))
_sym_db.RegisterMessage(EncounterRequest)


# @@protoc_insertion_point(module_scope)
