# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Requests/FortDetailsRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Requests/FortDetailsRequest.proto',
  package='Protos.Requests',
  syntax='proto3',
  serialized_pb=_b('\n!Requests/FortDetailsRequest.proto\x12\x0fProtos.Requests\"J\n\x12\x46ortDetailsRequest\x12\x0f\n\x07\x66ort_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FORTDETAILSREQUEST = _descriptor.Descriptor(
  name='FortDetailsRequest',
  full_name='Protos.Requests.FortDetailsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fort_id', full_name='Protos.Requests.FortDetailsRequest.fort_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Protos.Requests.FortDetailsRequest.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Protos.Requests.FortDetailsRequest.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['FortDetailsRequest'] = _FORTDETAILSREQUEST

FortDetailsRequest = _reflection.GeneratedProtocolMessageType('FortDetailsRequest', (_message.Message,), dict(
  DESCRIPTOR = _FORTDETAILSREQUEST,
  __module__ = 'Requests.FortDetailsRequest_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Requests.FortDetailsRequest)
  ))
_sym_db.RegisterMessage(FortDetailsRequest)


# @@protoc_insertion_point(module_scope)
