# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Requests/GetMapObjectsRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Requests/GetMapObjectsRequest.proto',
  package='Protos.Requests',
  syntax='proto3',
  serialized_pb=_b('\n#Requests/GetMapObjectsRequest.proto\x12\x0fProtos.Requests\"c\n\x14GetMapObjectsRequest\x12\x0f\n\x07\x63\x65ll_id\x18\x01 \x03(\x04\x12\x15\n\rsince_time_ms\x18\x02 \x03(\x03\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETMAPOBJECTSREQUEST = _descriptor.Descriptor(
  name='GetMapObjectsRequest',
  full_name='Protos.Requests.GetMapObjectsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cell_id', full_name='Protos.Requests.GetMapObjectsRequest.cell_id', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='since_time_ms', full_name='Protos.Requests.GetMapObjectsRequest.since_time_ms', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Protos.Requests.GetMapObjectsRequest.latitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Protos.Requests.GetMapObjectsRequest.longitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['GetMapObjectsRequest'] = _GETMAPOBJECTSREQUEST

GetMapObjectsRequest = _reflection.GeneratedProtocolMessageType('GetMapObjectsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETMAPOBJECTSREQUEST,
  __module__ = 'Requests.GetMapObjectsRequest_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Requests.GetMapObjectsRequest)
  ))
_sym_db.RegisterMessage(GetMapObjectsRequest)


# @@protoc_insertion_point(module_scope)
