# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Requests/GetPlayerRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Requests/GetPlayerRequest.proto',
  package='Protos.Requests',
  syntax='proto3',
  serialized_pb=_b('\n\x1fRequests/GetPlayerRequest.proto\x12\x0fProtos.Requests\"\x12\n\x10GetPlayerRequestb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETPLAYERREQUEST = _descriptor.Descriptor(
  name='GetPlayerRequest',
  full_name='Protos.Requests.GetPlayerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['GetPlayerRequest'] = _GETPLAYERREQUEST

GetPlayerRequest = _reflection.GeneratedProtocolMessageType('GetPlayerRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPLAYERREQUEST,
  __module__ = 'Requests.GetPlayerRequest_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Requests.GetPlayerRequest)
  ))
_sym_db.RegisterMessage(GetPlayerRequest)


# @@protoc_insertion_point(module_scope)
