# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Requests/RecycleInventoryItemRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Enums import InventoryEnums_pb2 as Enums_dot_InventoryEnums__pb2

from Enums.InventoryEnums_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Requests/RecycleInventoryItemRequest.proto',
  package='Protos.Requests',
  syntax='proto3',
  serialized_pb=_b('\n*Requests/RecycleInventoryItemRequest.proto\x12\x0fProtos.Requests\x1a\x1a\x45nums/InventoryEnums.proto\"S\n\x1bRecycleInventoryItemRequest\x12%\n\x07item_id\x18\x01 \x01(\x0e\x32\x14.Protos.Enums.ItemId\x12\r\n\x05\x63ount\x18\x02 \x01(\x05P\x00\x62\x06proto3')
  ,
  dependencies=[Enums_dot_InventoryEnums__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RECYCLEINVENTORYITEMREQUEST = _descriptor.Descriptor(
  name='RecycleInventoryItemRequest',
  full_name='Protos.Requests.RecycleInventoryItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='Protos.Requests.RecycleInventoryItemRequest.item_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='Protos.Requests.RecycleInventoryItemRequest.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=174,
)

_RECYCLEINVENTORYITEMREQUEST.fields_by_name['item_id'].enum_type = Enums_dot_InventoryEnums__pb2._ITEMID
DESCRIPTOR.message_types_by_name['RecycleInventoryItemRequest'] = _RECYCLEINVENTORYITEMREQUEST

RecycleInventoryItemRequest = _reflection.GeneratedProtocolMessageType('RecycleInventoryItemRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECYCLEINVENTORYITEMREQUEST,
  __module__ = 'Requests.RecycleInventoryItemRequest_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Requests.RecycleInventoryItemRequest)
  ))
_sym_db.RegisterMessage(RecycleInventoryItemRequest)


# @@protoc_insertion_point(module_scope)
