# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Player/InventoryItem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Player import InventoryItemData_pb2 as Player_dot_InventoryItemData__pb2
Pokemon_dot_Pokemon__pb2 = Player_dot_InventoryItemData__pb2.Pokemon_dot_Pokemon__pb2
Enums_dot_PokemonEnums__pb2 = Player_dot_InventoryItemData__pb2.Enums_dot_PokemonEnums__pb2
Player_dot_Item__pb2 = Player_dot_InventoryItemData__pb2.Player_dot_Item__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryItemData__pb2.Enums_dot_PlayerEnums__pb2
Pokemon_dot_PokedexEntry__pb2 = Player_dot_InventoryItemData__pb2.Pokemon_dot_PokedexEntry__pb2
Player_dot_PlayerStats__pb2 = Player_dot_InventoryItemData__pb2.Player_dot_PlayerStats__pb2
Player_dot_PlayerCurrency__pb2 = Player_dot_InventoryItemData__pb2.Player_dot_PlayerCurrency__pb2
Player_dot_PlayerCamera__pb2 = Player_dot_InventoryItemData__pb2.Player_dot_PlayerCamera__pb2
Player_dot_InventoryUpgrade__pb2 = Player_dot_InventoryItemData__pb2.Player_dot_InventoryUpgrade__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryItemData__pb2.Enums_dot_PlayerEnums__pb2
Player_dot_AppliedItem__pb2 = Player_dot_InventoryItemData__pb2.Player_dot_AppliedItem__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryItemData__pb2.Enums_dot_PlayerEnums__pb2
Player_dot_EggIncubator__pb2 = Player_dot_InventoryItemData__pb2.Player_dot_EggIncubator__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryItemData__pb2.Enums_dot_PlayerEnums__pb2
Pokemon_dot_PokemonFamily__pb2 = Player_dot_InventoryItemData__pb2.Pokemon_dot_PokemonFamily__pb2
Enums_dot_PokemonEnums__pb2 = Player_dot_InventoryItemData__pb2.Enums_dot_PokemonEnums__pb2

from Player.InventoryItemData_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Player/InventoryItem.proto',
  package='Protos.Player',
  syntax='proto3',
  serialized_pb=_b('\n\x1aPlayer/InventoryItem.proto\x12\rProtos.Player\x1a\x1ePlayer/InventoryItemData.proto\"\x87\x01\n\rInventoryItem\x12\x1d\n\x15modified_timestamp_ms\x18\x01 \x01(\x03\x12\x18\n\x10\x64\x65leted_item_key\x18\x02 \x01(\x03\x12=\n\x13inventory_item_data\x18\x03 \x01(\x0b\x32 .Protos.Player.InventoryItemDataP\x00\x62\x06proto3')
  ,
  dependencies=[Player_dot_InventoryItemData__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INVENTORYITEM = _descriptor.Descriptor(
  name='InventoryItem',
  full_name='Protos.Player.InventoryItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modified_timestamp_ms', full_name='Protos.Player.InventoryItem.modified_timestamp_ms', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deleted_item_key', full_name='Protos.Player.InventoryItem.deleted_item_key', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inventory_item_data', full_name='Protos.Player.InventoryItem.inventory_item_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=213,
)

_INVENTORYITEM.fields_by_name['inventory_item_data'].message_type = Player_dot_InventoryItemData__pb2._INVENTORYITEMDATA
DESCRIPTOR.message_types_by_name['InventoryItem'] = _INVENTORYITEM

InventoryItem = _reflection.GeneratedProtocolMessageType('InventoryItem', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORYITEM,
  __module__ = 'Player.InventoryItem_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Player.InventoryItem)
  ))
_sym_db.RegisterMessage(InventoryItem)


# @@protoc_insertion_point(module_scope)
