# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Player/InventoryUpgrade.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Enums import PlayerEnums_pb2 as Enums_dot_PlayerEnums__pb2

from Enums.PlayerEnums_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Player/InventoryUpgrade.proto',
  package='Protos.Player',
  syntax='proto3',
  serialized_pb=_b('\n\x1dPlayer/InventoryUpgrade.proto\x12\rProtos.Player\x1a\x17\x45nums/PlayerEnums.proto\"\x8e\x01\n\x10InventoryUpgrade\x12$\n\x04item\x18\x01 \x01(\x0e\x32\x16.Protos.Enums.ItemType\x12\x38\n\x0cupgrade_type\x18\x02 \x01(\x0e\x32\".Protos.Enums.InventoryUpgradeType\x12\x1a\n\x12\x61\x64\x64itional_storage\x18\x03 \x01(\x05P\x00\x62\x06proto3')
  ,
  dependencies=[Enums_dot_PlayerEnums__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INVENTORYUPGRADE = _descriptor.Descriptor(
  name='InventoryUpgrade',
  full_name='Protos.Player.InventoryUpgrade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='Protos.Player.InventoryUpgrade.item', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upgrade_type', full_name='Protos.Player.InventoryUpgrade.upgrade_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='additional_storage', full_name='Protos.Player.InventoryUpgrade.additional_storage', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=216,
)

_INVENTORYUPGRADE.fields_by_name['item'].enum_type = Enums_dot_PlayerEnums__pb2._ITEMTYPE
_INVENTORYUPGRADE.fields_by_name['upgrade_type'].enum_type = Enums_dot_PlayerEnums__pb2._INVENTORYUPGRADETYPE
DESCRIPTOR.message_types_by_name['InventoryUpgrade'] = _INVENTORYUPGRADE

InventoryUpgrade = _reflection.GeneratedProtocolMessageType('InventoryUpgrade', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORYUPGRADE,
  __module__ = 'Player.InventoryUpgrade_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Player.InventoryUpgrade)
  ))
_sym_db.RegisterMessage(InventoryUpgrade)


# @@protoc_insertion_point(module_scope)
