# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Player/InventoryDelta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Player import InventoryItem_pb2 as Player_dot_InventoryItem__pb2
Player_dot_InventoryItemData__pb2 = Player_dot_InventoryItem__pb2.Player_dot_InventoryItemData__pb2
Pokemon_dot_Pokemon__pb2 = Player_dot_InventoryItem__pb2.Pokemon_dot_Pokemon__pb2
Enums_dot_PokemonEnums__pb2 = Player_dot_InventoryItem__pb2.Enums_dot_PokemonEnums__pb2
Player_dot_Item__pb2 = Player_dot_InventoryItem__pb2.Player_dot_Item__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryItem__pb2.Enums_dot_PlayerEnums__pb2
Pokemon_dot_PokedexEntry__pb2 = Player_dot_InventoryItem__pb2.Pokemon_dot_PokedexEntry__pb2
Player_dot_PlayerStats__pb2 = Player_dot_InventoryItem__pb2.Player_dot_PlayerStats__pb2
Player_dot_PlayerCurrency__pb2 = Player_dot_InventoryItem__pb2.Player_dot_PlayerCurrency__pb2
Player_dot_PlayerCamera__pb2 = Player_dot_InventoryItem__pb2.Player_dot_PlayerCamera__pb2
Player_dot_InventoryUpgrade__pb2 = Player_dot_InventoryItem__pb2.Player_dot_InventoryUpgrade__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryItem__pb2.Enums_dot_PlayerEnums__pb2
Player_dot_AppliedItem__pb2 = Player_dot_InventoryItem__pb2.Player_dot_AppliedItem__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryItem__pb2.Enums_dot_PlayerEnums__pb2
Player_dot_EggIncubator__pb2 = Player_dot_InventoryItem__pb2.Player_dot_EggIncubator__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryItem__pb2.Enums_dot_PlayerEnums__pb2
Pokemon_dot_PokemonFamily__pb2 = Player_dot_InventoryItem__pb2.Pokemon_dot_PokemonFamily__pb2
Enums_dot_PokemonEnums__pb2 = Player_dot_InventoryItem__pb2.Enums_dot_PokemonEnums__pb2

from Player.InventoryItem_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Player/InventoryDelta.proto',
  package='Protos.Player',
  syntax='proto3',
  serialized_pb=_b('\n\x1bPlayer/InventoryDelta.proto\x12\rProtos.Player\x1a\x1aPlayer/InventoryItem.proto\"\x80\x01\n\x0eInventoryDelta\x12\x1d\n\x15original_timestamp_ms\x18\x01 \x01(\x03\x12\x18\n\x10new_timestamp_ms\x18\x02 \x01(\x03\x12\x35\n\x0finventory_items\x18\x03 \x03(\x0b\x32\x1c.Protos.Player.InventoryItemP\x00\x62\x06proto3')
  ,
  dependencies=[Player_dot_InventoryItem__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INVENTORYDELTA = _descriptor.Descriptor(
  name='InventoryDelta',
  full_name='Protos.Player.InventoryDelta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='original_timestamp_ms', full_name='Protos.Player.InventoryDelta.original_timestamp_ms', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_timestamp_ms', full_name='Protos.Player.InventoryDelta.new_timestamp_ms', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inventory_items', full_name='Protos.Player.InventoryDelta.inventory_items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=203,
)

_INVENTORYDELTA.fields_by_name['inventory_items'].message_type = Player_dot_InventoryItem__pb2._INVENTORYITEM
DESCRIPTOR.message_types_by_name['InventoryDelta'] = _INVENTORYDELTA

InventoryDelta = _reflection.GeneratedProtocolMessageType('InventoryDelta', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORYDELTA,
  __module__ = 'Player.InventoryDelta_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Player.InventoryDelta)
  ))
_sym_db.RegisterMessage(InventoryDelta)


# @@protoc_insertion_point(module_scope)
