# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Player/InventoryItemData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Pokemon import Pokemon_pb2 as Pokemon_dot_Pokemon__pb2
Enums_dot_PokemonEnums__pb2 = Pokemon_dot_Pokemon__pb2.Enums_dot_PokemonEnums__pb2
from Player import Item_pb2 as Player_dot_Item__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_Item__pb2.Enums_dot_PlayerEnums__pb2
from Pokemon import PokedexEntry_pb2 as Pokemon_dot_PokedexEntry__pb2
from Player import PlayerStats_pb2 as Player_dot_PlayerStats__pb2
from Player import PlayerCurrency_pb2 as Player_dot_PlayerCurrency__pb2
from Player import PlayerCamera_pb2 as Player_dot_PlayerCamera__pb2
from Player import InventoryUpgrade_pb2 as Player_dot_InventoryUpgrade__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_InventoryUpgrade__pb2.Enums_dot_PlayerEnums__pb2
from Player import AppliedItem_pb2 as Player_dot_AppliedItem__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_AppliedItem__pb2.Enums_dot_PlayerEnums__pb2
from Player import EggIncubator_pb2 as Player_dot_EggIncubator__pb2
Enums_dot_PlayerEnums__pb2 = Player_dot_EggIncubator__pb2.Enums_dot_PlayerEnums__pb2
from Pokemon import PokemonFamily_pb2 as Pokemon_dot_PokemonFamily__pb2
Enums_dot_PokemonEnums__pb2 = Pokemon_dot_PokemonFamily__pb2.Enums_dot_PokemonEnums__pb2

from Pokemon.Pokemon_pb2 import *
from Player.Item_pb2 import *
from Pokemon.PokedexEntry_pb2 import *
from Player.PlayerStats_pb2 import *
from Player.PlayerCurrency_pb2 import *
from Player.PlayerCamera_pb2 import *
from Player.InventoryUpgrade_pb2 import *
from Player.AppliedItem_pb2 import *
from Player.EggIncubator_pb2 import *
from Pokemon.PokemonFamily_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Player/InventoryItemData.proto',
  package='Protos.Player',
  syntax='proto3',
  serialized_pb=_b('\n\x1ePlayer/InventoryItemData.proto\x12\rProtos.Player\x1a\x15Pokemon/Pokemon.proto\x1a\x11Player/Item.proto\x1a\x1aPokemon/PokedexEntry.proto\x1a\x18Player/PlayerStats.proto\x1a\x1bPlayer/PlayerCurrency.proto\x1a\x19Player/PlayerCamera.proto\x1a\x1dPlayer/InventoryUpgrade.proto\x1a\x18Player/AppliedItem.proto\x1a\x19Player/EggIncubator.proto\x1a\x1bPokemon/PokemonFamily.proto\"P\n\x11InventoryUpgrades\x12;\n\x12inventory_upgrades\x18\x01 \x03(\x0b\x32\x1f.Protos.Player.InventoryUpgrade\"C\n\rEggIncubators\x12\x32\n\regg_incubator\x18\x01 \x03(\x0b\x32\x1b.Protos.Player.EggIncubator\"8\n\x0c\x41ppliedItems\x12(\n\x04item\x18\x04 \x03(\x0b\x32\x1a.Protos.Player.AppliedItem\"\x92\x04\n\x11InventoryItemData\x12(\n\x07pokemon\x18\x01 \x01(\x0b\x32\x17.Protos.Pokemon.Pokemon\x12!\n\x04item\x18\x02 \x01(\x0b\x32\x13.Protos.Player.Item\x12\x33\n\rpokedex_entry\x18\x03 \x01(\x0b\x32\x1c.Protos.Pokemon.PokedexEntry\x12\x30\n\x0cplayer_stats\x18\x04 \x01(\x0b\x32\x1a.Protos.Player.PlayerStats\x12\x36\n\x0fplayer_currency\x18\x05 \x01(\x0b\x32\x1d.Protos.Player.PlayerCurrency\x12\x32\n\rplayer_camera\x18\x06 \x01(\x0b\x32\x1b.Protos.Player.PlayerCamera\x12<\n\x12inventory_upgrades\x18\x07 \x01(\x0b\x32 .Protos.Player.InventoryUpgrades\x12\x32\n\rapplied_items\x18\x08 \x01(\x0b\x32\x1b.Protos.Player.AppliedItems\x12\x34\n\x0e\x65gg_incubators\x18\t \x01(\x0b\x32\x1c.Protos.Player.EggIncubators\x12\x35\n\x0epokemon_family\x18\n \x01(\x0b\x32\x1d.Protos.Pokemon.PokemonFamilyP\x00P\x01P\x02P\x03P\x04P\x05P\x06P\x07P\x08P\tb\x06proto3')
  ,
  dependencies=[Pokemon_dot_Pokemon__pb2.DESCRIPTOR,Player_dot_Item__pb2.DESCRIPTOR,Pokemon_dot_PokedexEntry__pb2.DESCRIPTOR,Player_dot_PlayerStats__pb2.DESCRIPTOR,Player_dot_PlayerCurrency__pb2.DESCRIPTOR,Player_dot_PlayerCamera__pb2.DESCRIPTOR,Player_dot_InventoryUpgrade__pb2.DESCRIPTOR,Player_dot_AppliedItem__pb2.DESCRIPTOR,Player_dot_EggIncubator__pb2.DESCRIPTOR,Pokemon_dot_PokemonFamily__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INVENTORYUPGRADES = _descriptor.Descriptor(
  name='InventoryUpgrades',
  full_name='Protos.Player.InventoryUpgrades',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inventory_upgrades', full_name='Protos.Player.InventoryUpgrades.inventory_upgrades', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=394,
)


_EGGINCUBATORS = _descriptor.Descriptor(
  name='EggIncubators',
  full_name='Protos.Player.EggIncubators',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='egg_incubator', full_name='Protos.Player.EggIncubators.egg_incubator', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=463,
)


_APPLIEDITEMS = _descriptor.Descriptor(
  name='AppliedItems',
  full_name='Protos.Player.AppliedItems',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='Protos.Player.AppliedItems.item', index=0,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=521,
)


_INVENTORYITEMDATA = _descriptor.Descriptor(
  name='InventoryItemData',
  full_name='Protos.Player.InventoryItemData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pokemon', full_name='Protos.Player.InventoryItemData.pokemon', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='Protos.Player.InventoryItemData.item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokedex_entry', full_name='Protos.Player.InventoryItemData.pokedex_entry', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_stats', full_name='Protos.Player.InventoryItemData.player_stats', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_currency', full_name='Protos.Player.InventoryItemData.player_currency', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_camera', full_name='Protos.Player.InventoryItemData.player_camera', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inventory_upgrades', full_name='Protos.Player.InventoryItemData.inventory_upgrades', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='applied_items', full_name='Protos.Player.InventoryItemData.applied_items', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='egg_incubators', full_name='Protos.Player.InventoryItemData.egg_incubators', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokemon_family', full_name='Protos.Player.InventoryItemData.pokemon_family', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=1054,
)

_INVENTORYUPGRADES.fields_by_name['inventory_upgrades'].message_type = Player_dot_InventoryUpgrade__pb2._INVENTORYUPGRADE
_EGGINCUBATORS.fields_by_name['egg_incubator'].message_type = Player_dot_EggIncubator__pb2._EGGINCUBATOR
_APPLIEDITEMS.fields_by_name['item'].message_type = Player_dot_AppliedItem__pb2._APPLIEDITEM
_INVENTORYITEMDATA.fields_by_name['pokemon'].message_type = Pokemon_dot_Pokemon__pb2._POKEMON
_INVENTORYITEMDATA.fields_by_name['item'].message_type = Player_dot_Item__pb2._ITEM
_INVENTORYITEMDATA.fields_by_name['pokedex_entry'].message_type = Pokemon_dot_PokedexEntry__pb2._POKEDEXENTRY
_INVENTORYITEMDATA.fields_by_name['player_stats'].message_type = Player_dot_PlayerStats__pb2._PLAYERSTATS
_INVENTORYITEMDATA.fields_by_name['player_currency'].message_type = Player_dot_PlayerCurrency__pb2._PLAYERCURRENCY
_INVENTORYITEMDATA.fields_by_name['player_camera'].message_type = Player_dot_PlayerCamera__pb2._PLAYERCAMERA
_INVENTORYITEMDATA.fields_by_name['inventory_upgrades'].message_type = _INVENTORYUPGRADES
_INVENTORYITEMDATA.fields_by_name['applied_items'].message_type = _APPLIEDITEMS
_INVENTORYITEMDATA.fields_by_name['egg_incubators'].message_type = _EGGINCUBATORS
_INVENTORYITEMDATA.fields_by_name['pokemon_family'].message_type = Pokemon_dot_PokemonFamily__pb2._POKEMONFAMILY
DESCRIPTOR.message_types_by_name['InventoryUpgrades'] = _INVENTORYUPGRADES
DESCRIPTOR.message_types_by_name['EggIncubators'] = _EGGINCUBATORS
DESCRIPTOR.message_types_by_name['AppliedItems'] = _APPLIEDITEMS
DESCRIPTOR.message_types_by_name['InventoryItemData'] = _INVENTORYITEMDATA

InventoryUpgrades = _reflection.GeneratedProtocolMessageType('InventoryUpgrades', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORYUPGRADES,
  __module__ = 'Player.InventoryItemData_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Player.InventoryUpgrades)
  ))
_sym_db.RegisterMessage(InventoryUpgrades)

EggIncubators = _reflection.GeneratedProtocolMessageType('EggIncubators', (_message.Message,), dict(
  DESCRIPTOR = _EGGINCUBATORS,
  __module__ = 'Player.InventoryItemData_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Player.EggIncubators)
  ))
_sym_db.RegisterMessage(EggIncubators)

AppliedItems = _reflection.GeneratedProtocolMessageType('AppliedItems', (_message.Message,), dict(
  DESCRIPTOR = _APPLIEDITEMS,
  __module__ = 'Player.InventoryItemData_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Player.AppliedItems)
  ))
_sym_db.RegisterMessage(AppliedItems)

InventoryItemData = _reflection.GeneratedProtocolMessageType('InventoryItemData', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORYITEMDATA,
  __module__ = 'Player.InventoryItemData_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Player.InventoryItemData)
  ))
_sym_db.RegisterMessage(InventoryItemData)


# @@protoc_insertion_point(module_scope)
