# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Player/Item.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Enums import PlayerEnums_pb2 as Enums_dot_PlayerEnums__pb2

from Enums.PlayerEnums_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Player/Item.proto',
  package='Protos.Player',
  syntax='proto3',
  serialized_pb=_b('\n\x11Player/Item.proto\x12\rProtos.Player\x1a\x17\x45nums/PlayerEnums.proto\"K\n\x04Item\x12$\n\x04item\x18\x01 \x01(\x0e\x32\x16.Protos.Enums.ItemType\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x0e\n\x06unseen\x18\x03 \x01(\x08P\x00\x62\x06proto3')
  ,
  dependencies=[Enums_dot_PlayerEnums__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Protos.Player.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='Protos.Player.Item.item', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='Protos.Player.Item.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unseen', full_name='Protos.Player.Item.unseen', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=136,
)

_ITEM.fields_by_name['item'].enum_type = Enums_dot_PlayerEnums__pb2._ITEMTYPE
DESCRIPTOR.message_types_by_name['Item'] = _ITEM

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'Player.Item_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Player.Item)
  ))
_sym_db.RegisterMessage(Item)


# @@protoc_insertion_point(module_scope)
