# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Pokemon/PokemonFamily.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Enums import PokemonEnums_pb2 as Enums_dot_PokemonEnums__pb2

from Enums.PokemonEnums_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Pokemon/PokemonFamily.proto',
  package='Protos.Pokemon',
  syntax='proto3',
  serialized_pb=_b('\n\x1bPokemon/PokemonFamily.proto\x12\x0eProtos.Pokemon\x1a\x18\x45nums/PokemonEnums.proto\"P\n\rPokemonFamily\x12\x30\n\tfamily_id\x18\x01 \x01(\x0e\x32\x1d.Protos.Enums.PokemonFamilyId\x12\r\n\x05\x63\x61ndy\x18\x02 \x01(\x05P\x00\x62\x06proto3')
  ,
  dependencies=[Enums_dot_PokemonEnums__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POKEMONFAMILY = _descriptor.Descriptor(
  name='PokemonFamily',
  full_name='Protos.Pokemon.PokemonFamily',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='family_id', full_name='Protos.Pokemon.PokemonFamily.family_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='candy', full_name='Protos.Pokemon.PokemonFamily.candy', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=153,
)

_POKEMONFAMILY.fields_by_name['family_id'].enum_type = Enums_dot_PokemonEnums__pb2._POKEMONFAMILYID
DESCRIPTOR.message_types_by_name['PokemonFamily'] = _POKEMONFAMILY

PokemonFamily = _reflection.GeneratedProtocolMessageType('PokemonFamily', (_message.Message,), dict(
  DESCRIPTOR = _POKEMONFAMILY,
  __module__ = 'Pokemon.PokemonFamily_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Pokemon.PokemonFamily)
  ))
_sym_db.RegisterMessage(PokemonFamily)


# @@protoc_insertion_point(module_scope)
