# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Map/MapCell.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Map import SpawnPoint_pb2 as Map_dot_SpawnPoint__pb2
from Map.Fort import FortData_pb2 as Map_dot_Fort_dot_FortData__pb2
Enums_dot_PlayerEnums__pb2 = Map_dot_Fort_dot_FortData__pb2.Enums_dot_PlayerEnums__pb2
Enums_dot_PokemonEnums__pb2 = Map_dot_Fort_dot_FortData__pb2.Enums_dot_PokemonEnums__pb2
Enums_dot_FortEnums__pb2 = Map_dot_Fort_dot_FortData__pb2.Enums_dot_FortEnums__pb2
Map_dot_Fort_dot_FortLureInfo__pb2 = Map_dot_Fort_dot_FortData__pb2.Map_dot_Fort_dot_FortLureInfo__pb2
Enums_dot_PokemonEnums__pb2 = Map_dot_Fort_dot_FortData__pb2.Enums_dot_PokemonEnums__pb2
from Map.Fort import FortSummary_pb2 as Map_dot_Fort_dot_FortSummary__pb2
from Map.Pokemon import OneStepPokemon_pb2 as Map_dot_Pokemon_dot_OneStepPokemon__pb2
Enums_dot_PokemonEnums__pb2 = Map_dot_Pokemon_dot_OneStepPokemon__pb2.Enums_dot_PokemonEnums__pb2
from Map.Pokemon import TwoStepsPokemon_pb2 as Map_dot_Pokemon_dot_TwoStepsPokemon__pb2
Pokemon_dot_PokemonDetails__pb2 = Map_dot_Pokemon_dot_TwoStepsPokemon__pb2.Pokemon_dot_PokemonDetails__pb2
from Map.Pokemon import ThreeStepsPokemon_pb2 as Map_dot_Pokemon_dot_ThreeStepsPokemon__pb2
Enums_dot_PokemonEnums__pb2 = Map_dot_Pokemon_dot_ThreeStepsPokemon__pb2.Enums_dot_PokemonEnums__pb2

from Map.SpawnPoint_pb2 import *
from Map.Fort.FortData_pb2 import *
from Map.Fort.FortSummary_pb2 import *
from Map.Pokemon.OneStepPokemon_pb2 import *
from Map.Pokemon.TwoStepsPokemon_pb2 import *
from Map.Pokemon.ThreeStepsPokemon_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Map/MapCell.proto',
  package='Protos.Map',
  syntax='proto3',
  serialized_pb=_b('\n\x11Map/MapCell.proto\x12\nProtos.Map\x1a\x14Map/SpawnPoint.proto\x1a\x17Map/Fort/FortData.proto\x1a\x1aMap/Fort/FortSummary.proto\x1a Map/Pokemon/OneStepPokemon.proto\x1a!Map/Pokemon/TwoStepsPokemon.proto\x1a#Map/Pokemon/ThreeStepsPokemon.proto\"\xf2\x03\n\x07MapCell\x12\x12\n\ns2_cell_id\x18\x01 \x01(\x04\x12\x1c\n\x14\x63urrent_timestamp_ms\x18\x02 \x01(\x03\x12(\n\x05\x66orts\x18\x03 \x03(\x0b\x32\x19.Protos.Map.Fort.FortData\x12+\n\x0bspawn_point\x18\x04 \x03(\x0b\x32\x16.Protos.Map.SpawnPoint\x12>\n\x11two_steps_pokemon\x18\x05 \x03(\x0b\x32#.Protos.Map.Pokemon.TwoStepsPokemon\x12\x16\n\x0e\x64\x65leted_object\x18\x06 \x03(\t\x12\x19\n\x11is_truncated_list\x18\x07 \x01(\x08\x12\x32\n\x0c\x66ort_summary\x18\x08 \x03(\x0b\x32\x1c.Protos.Map.Fort.FortSummary\x12\x35\n\x15\x64\x65\x63imated_spawn_point\x18\t \x03(\x0b\x32\x16.Protos.Map.SpawnPoint\x12<\n\x10one_step_pokemon\x18\n \x03(\x0b\x32\".Protos.Map.Pokemon.OneStepPokemon\x12\x42\n\x13three_steps_pokemon\x18\x0b \x03(\x0b\x32%.Protos.Map.Pokemon.ThreeStepsPokemonP\x00P\x01P\x02P\x03P\x04P\x05\x62\x06proto3')
  ,
  dependencies=[Map_dot_SpawnPoint__pb2.DESCRIPTOR,Map_dot_Fort_dot_FortData__pb2.DESCRIPTOR,Map_dot_Fort_dot_FortSummary__pb2.DESCRIPTOR,Map_dot_Pokemon_dot_OneStepPokemon__pb2.DESCRIPTOR,Map_dot_Pokemon_dot_TwoStepsPokemon__pb2.DESCRIPTOR,Map_dot_Pokemon_dot_ThreeStepsPokemon__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MAPCELL = _descriptor.Descriptor(
  name='MapCell',
  full_name='Protos.Map.MapCell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s2_cell_id', full_name='Protos.Map.MapCell.s2_cell_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_timestamp_ms', full_name='Protos.Map.MapCell.current_timestamp_ms', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forts', full_name='Protos.Map.MapCell.forts', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spawn_point', full_name='Protos.Map.MapCell.spawn_point', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='two_steps_pokemon', full_name='Protos.Map.MapCell.two_steps_pokemon', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deleted_object', full_name='Protos.Map.MapCell.deleted_object', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_truncated_list', full_name='Protos.Map.MapCell.is_truncated_list', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fort_summary', full_name='Protos.Map.MapCell.fort_summary', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='decimated_spawn_point', full_name='Protos.Map.MapCell.decimated_spawn_point', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='one_step_pokemon', full_name='Protos.Map.MapCell.one_step_pokemon', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='three_steps_pokemon', full_name='Protos.Map.MapCell.three_steps_pokemon', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=713,
)

_MAPCELL.fields_by_name['forts'].message_type = Map_dot_Fort_dot_FortData__pb2._FORTDATA
_MAPCELL.fields_by_name['spawn_point'].message_type = Map_dot_SpawnPoint__pb2._SPAWNPOINT
_MAPCELL.fields_by_name['two_steps_pokemon'].message_type = Map_dot_Pokemon_dot_TwoStepsPokemon__pb2._TWOSTEPSPOKEMON
_MAPCELL.fields_by_name['fort_summary'].message_type = Map_dot_Fort_dot_FortSummary__pb2._FORTSUMMARY
_MAPCELL.fields_by_name['decimated_spawn_point'].message_type = Map_dot_SpawnPoint__pb2._SPAWNPOINT
_MAPCELL.fields_by_name['one_step_pokemon'].message_type = Map_dot_Pokemon_dot_OneStepPokemon__pb2._ONESTEPPOKEMON
_MAPCELL.fields_by_name['three_steps_pokemon'].message_type = Map_dot_Pokemon_dot_ThreeStepsPokemon__pb2._THREESTEPSPOKEMON
DESCRIPTOR.message_types_by_name['MapCell'] = _MAPCELL

MapCell = _reflection.GeneratedProtocolMessageType('MapCell', (_message.Message,), dict(
  DESCRIPTOR = _MAPCELL,
  __module__ = 'Map.MapCell_pb2'
  # @@protoc_insertion_point(class_scope:Protos.Map.MapCell)
  ))
_sym_db.RegisterMessage(MapCell)


# @@protoc_insertion_point(module_scope)
